"""add a preference table

Revision ID: 981333c8df20
Revises: 2cff67d383a6
Create Date: 2021-09-22 10:52:10.634076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981333c8df20'
down_revision = '2cff67d383a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='preference_pkey')
    )
    op.drop_table('genre')
    # ### end Alembic commands ###
