"""change the name of the genre to unique

Revision ID: cb9e3b2eb844
Revises: e3e2b41bb941
Create Date: 2021-09-22 12:45:07.898633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9e3b2eb844'
down_revision = 'e3e2b41bb941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    # ### end Alembic commands ###
